[package]
name = "pkg"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }

logger = { workspace = true }
libpkg = { path = "libpkg", default-features = false }

[lints]
workspace = true
